[package]
name = "photo-selector"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10", features = ["image"] }
image = "0.24"
walkdir = "2.4"
kamadak-exif = "0.5"
rayon = "1.8" 